apiVersion: v1
kind: Namespace
metadata:
  name: semaphore
  labels:
    security.openshift.io/scc.podSecurityLabelSync: 'false'
    openshift.io/run-level: '0'    
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged  

