apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-persistent-storage
  labels:
    app: seemaphore-web
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
