apiVersion: v1
kind: Service
metadata:
  name: semaphore-mysql   # will be used as a value in
  labels:                 # SEMAPHORE_DB_HOST in wordpress-deploy.yml
    app: wordpress
  namespace: semaphore
spec:
  ports:
    - port: 3306
  selector:
    app: semaphore
    tier: mysql
  clusterIP: None
