apiVersion: v1
kind: Service
metadata:
  name: semaphore
  labels:
    app: semaphore-web
  namespace: semaphore
spec:
  ports:
    - port: 3000
  selector:
    app: semaphore-web
    tier: frontend
  type: ClusterIP
